import Queue
from Logger import *

class TaskDispatcher(Queue.Queue):
    """ queue of tasks generated by other tasks """
    def run(self):
        while 1:
            task = self.get()
            task.run()
            if task._done == False:
                self.add(task)