import Queue
from Logger import *

__author__="alstein"
__date__ ="$11.11.2010 15:06:23$"

class TaskDispatcher(Queue.Queue):
    """ queue of tasks generated by other tasks """
    def run(self):
        while 1:
            task = self.get()
            task.run()