import Queue
from Logger import *

class TaskDispatcher(Queue.PriorityQueue):
    """ queue of tasks generated by other tasks """
    def run(self):
        while 1:
            task = self.get()[1]
            task.run()